---
title: "Parentage Analysis"
favicon: "https://github.com/ShannonKitchen/ShannonKitchen.github.io/blob/main/ParentageAnalysis_files/libs/noto-nest-with-eggs.ico"
format:
  html:
    theme: united
    fontsize: 16px
engine: knitr
---

```{scss, echo = FALSE}
.callout.callout-style-simple>div.callout-header{
  border-bottom: none;
  font-size: 18px;
  font-weight: 600;
  opacity: 75%;
}
div{
  &.callout-important.callout {
    border-left-color: gray;
  }
}
div{
  &.callout-important.callout-titled .callout-icon::before {
    background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" style="fill: rgb(128, 128, 128)" class="bi bi-exclamation-circle" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/><path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/></svg>');
  }
}

.blockquote {
    font-size: inherit;
    padding-left: 1rem;
    padding-right: 1.5rem;
    color: #a8a36f;
}

blockquote {
    margin: 0 0 1rem;
    padding: .625rem 1.25rem;
    border-left: .25rem solid #b7b077;
}
```

> ### Meeting 4/30/2025
>
> -   Based on spending timeline, we decided to reach out to <https://www.floragenex.com> and inquire about ddRAD-seq services
>
>     -   Shannon's sister estimates \~\$52/sample
>
> -   Otherwise, Arizona gave the most information/low costs for microsatellite work

### Feather DNA Processing Protocols

-   <https://www.qiagen.com/us/resources/resourcedetail?id=a5a065dc-e287-4a61-b917-9792e25ab42f&lang=en>

-   <https://doi.org/10.1111/j.0908-8857.2005.03370.x>

-   <https://www.protocols.io/view/dna-extraction-from-feathers-261ge4q57v47/v1>

:::: {.callout-important collapse="true" style="border-color-left:gray" appearance="simple"}
### Email responses

::: {.panel-tabset style="font-size:14px"}
#### Wildlife Genetics (Canada)

Contact: David Paetkau, [dpaetkau\@wildlifegenetics.ca](mailto:dpaetkau@wildlifegenetics.ca){style="color:steelblue"}

Hi Shannon,

This is a genus that we haven't worked on before, so there is a bit to think about in terms of getting markers going. Normally we'd charge about US \$78 per sample for DNA extraction and 18-locus genotyping, plus about \$1000 per project for error-checking and reporting. But for the first go with a species there will extra costs associated with primer design and testing.

For a series of practical and technical reasons, we prefer to work with dinucleotide repeats over the tetras described in the Faircloth paper (I wasn't able to access the Fowler paper), and the Faircloth markers at least didn't show great variability - perhaps a characteristic of the study population, but perhaps to do with the loci themselves. Given the availability of a genome, my preference would be to search each chromosome for a tidy, long dinucleotide repeat locus, and design primers for about 50% more loci than we'd be aiming to use in the end; e.g. 27 loci if aiming for 18. We charge \$300 per locus to design and test primers, so that puts us about \$8000 down the road before we find out if we ended up with nice markers. We would use about 30 samples for marker testing, so there would be no subsequent need to genotype those 30 samples, but it does mean that the first round of work would be around \$5500 more expensive than a routine project on a species that we know.

In short, if it's a project that might extend for a number of years, and run to many hundreds of samples, the development cost isn't too out of line (we've done similar things for a multiyear gyrfalcon project that I'm quite pleased with), but for a one-off project it might strike you as too expensive.

With all the primer design and testing we'd need a solid 8 months to do a project like this.

Thoughts?

David

#### Oregon State- Epps Lab

Contact: Rachel Crowhurst, [Rachel.Crowhurst\@oregonstate.edu](mailto:Rachel.Crowhurst@oregonstate.edu){style="color:steelblue"}

Hi Shannon,

Thanks for your interest in our lab, and apologies for the delay in responding to you.

I looked through the first paper that you sent (Faircloth et al. 2006) and there are plenty of highly variable markers for bluebirds, which is great.  However, it looks like in that paper they ran every marker individually because they were characterizing new loci.  For us to try to estimate how much this would cost we’d need to see how many markers can be multiplexed in a single PCR reaction, as that can greatly influence the cost.  I could try to guess based on allele sizes, but it would be most helpful to see how someone else used these markers in a previously published study.  Unfortunately, I was unable to access the Fowler Neal thesis without a University of Arkansas login.  Would you be able to download the thesis and send it to me as a .pdf?   We typically charge about \$100 per sample for species that we’ve worked on before, for up to 3 panels of markers.  However, there is an initial cost for the labelled primers and since we do not have those on-hand, that would add approximately \$4000.  We would probably also need to build in a buffer for optimization runs, since it often takes a bit of tweaking before we can get a new primer/species system to work, even if we’re working off of a previously published study. 

Full disclosure – we specialize in mammalian samples (feces, blood, tissue) and although I’ve done some sexing work on blood from seabirds I do not have experience working with feathers.  In my reading I’ve seen published protocols wherein people use the same DNA extraction kit for feathers as we use for muscle (Qiagen DNEasy blood and tissue), with a few modifications.  However the Faircloth paper used DNA from blood and the PCR product sizes are very large (mostly 250-350bp) and it’s unclear to me whether the feather DNA would work as well for such large amplicons.  I’d like to see what methods and sample type were used in Jessica Fowler Neal’s study.  Once we have a better idea of how many markers we could fit into a single PCR reaction and what extraction methods would be best to try, we would be better positioned to estimate the cost and turnaround time.

Best, Rachel Crowhurst

#### East Stroudsburg University

Contact: Nicole Chinnici, [nchinnici\@esu.edu](mailto:nchinnici@esu.edu){style="color:steelblue"}

Hi Shannon

Thank you for your request. This is a service that we can assist you with. To better understand your project and get you an accurate quote, we need some additional information.

1.  Will you be selecting the microsatellites for your project?

2.  Will you purchase those microsatellites yourself, or would you like that included in our service?

3.  What is the timeframe you are looking to complete this project?

Thank you, Nicole

#### Arizona Genetics Core

Contact: Barbara Fransway, [bbf\@arizona.edu](mailto:bbf@arizona.edu){style="color:steelblue"}

Shannon- thank you for getting back to our lab.

I don’t have experience extracting DNA from feathers, this would have to be piloted with some samples and then we could discuss how to proceed after DNA QC and yield assessment.

For the updated costs-

Assume- 5 multiplexes per sample-  this will help keep the primer costs low and reduce the optimization effort. In addition, if there are markers that are “must have” vs “not critical” this will also be informative.

In short, rough costs are:

Once optimized- DNA extraction +QC \~\$12.50/sample PCR \$3.60/reaction (*5= \$18) Fragment analysis \$2.10/well (*5=\$10.50)

So production test costs would be about \$40/sample- this is Extraction, QC, PCR and Frag if we do 5 reactions per sample

Primer costs are \~\$85-\$100/locus \*18= \$1550-1800

Optimization: PCR- \$3.60/reaction, gel electrophoresis estimated \$60-90, and fragment analysis \$2.10/sample- the quantities of PCR and Frag depend on how complex the multiplex assays are. Assume \$500-600 for optimization

Estimated total- Pilot extraction/QC  (n=8) \$100 if successful then we proceed. DNA extraction/QC, PCR and FRAG (n=100) \$4000 Data Finishing \$420 Optimization \$600 Primers \$1800

So it looks like we are at about \$6900 for this project. This again greatly depends on the loci selected and how we multiplex them together. In addition the pilot DNA extraction and following QC will be a critical point prior to proceeding with the samples.

If you would like a more official quote please register for iLab and I can create one in this system for you. See registration instructions attached.

Thank you and I look forward to being in contact soon. Barbara
:::
::::

### Microsatellite Selection

::: {.callout style="background:#b7c4e5; border-color:#5d78a5"}
Characteristics for primer sets should be highly polymorphic (many alleles) to distinguish between closely related individuals, and should maintain HWE for reliable allele frequency data (i.e. H<sub>o</sub> ≈ H<sub>E</sub>)
:::

::: {.callout-note style="border-color:#b7b077" collapse="true" appearance="minimal"}
#### Main texts

-   **Faircloth et al. 2006**:

    <https://doi.org/10.1111/j.1471-8286.2006.01408.x>

    -   <u> Neal 2014</u>: chose *Sialia* 6, 15, 20, 23, 27, 28, 34, 36, 38 "based on successful amplification and a satisfactory number of alleles."

-   **Ferree et al 2008**:

    <https://doi.org/10.1111/j.1755-0998.2008.02265.x>

    -   Though primers labelled as *Smex*, tested on NC population of *S. sialis* as well

-   **Balenger et al. 2009:**

    <https://doi.org/10.1111/j.1600-048X.2009.04521.x>

    -   uses *Sailia*37 from Faircloth 2006, and 2 new primers (*EABL*007, *EABL*129).

-   **Stewart et al. 2009**:

    <https://doi.org/10.1007/s00265-009-0862-y>

    -   Uses *Pdo*5 (Griffith et al. 1999), a loci for paternity in HOSP, as well as other loci developed for other species. Only EABL specific loci from Balenger et al 2009.

-   **Gutiérrez et al. 2022**

    <https://www.biorxiv.org/content/10.1101/2022.05.26.493631v1.full.pdf>

    -   "Five fluorescently labeled primers were amplified: *Smex*9 (Ferree et al. 2008), *Smex*14 (Ferree et al. 2008), *Pdo*5 (Griffith et al. 1999), *Sialia*36 (Faircloth et al. 2006), and Sialia37 (Faircloth et al. 2006)... Each primer was selected based on previous amplification success using eastern bluebird DNA (Faircloth et al. 2006, Ferree et al. 2008, and Stewart et al. 2009)."
        -   The two *Smex* primers chosen had a significant deviation from Hardy–Weinberg equilibrium in this original paper--- my understanding is this is not desirable?? Possibly did some trouble shooting for their population to come to this selection?
:::

::: {.callout-note style="border-color:#b7b077" collapse="true" appearance="minimal"}
#### Additional texts

-   **Liu 2009:** Chose *Sailia* 11,22,27,36,37, *EABL*129, and *MOBL*47,49,53,86b from Balenger et al. 2009 (likely an early copy? Only 49 & 87 published). *MOBL*53 & *Sailia*22 had HWE deviation.

-   **Avery et al. 2013:** selected 12 loci from Faircloth 2006 (those without sig. HWE deviation and with adequate \# of alleles)

-   **Dickinson et al. 2016 & Ferree et al. 2010:** selected 11 microsatellites from Ferree 2008 paper- *Smex* 2,4,5, 7-14

    -   In other words, they selected primers that did not deviate from HWE for western bluebirds
        -   For EABL, this would be *Smex* 2-8,10,12,13 *(15 borderline)*

            -   whittling it down more: 3, 5, 6, 7, 12, 13 are best for HWE and allele no.

-   **Joly 2024:** Mountain Bluebirds study, Chose *Sailia* 37, *EABL*129, and *Smex* 6,8,10,13
:::

::: {.callout style="background:thistle; border-color:#947d9c"}
Based on HWE and allele #, it seems like these are good candidates?

Faircloth- *Sailia* 11, 22, 28, 37 (trinucleotide)

Ferree - *Smex* 3,5,6,7,12,13 (dinucleotide)

Balenger - *EABL*007, *EABL*129, (Maybe *MOBL*49, *MOBL*87?) (dinucleotide)

→ Likely would want to do somewhere between 6-10 loci minimum (with 3-5 primer sets florescent labelled per multiplex PCR)
:::

### Other relevant info

-   Eastern Bluebird whole genome assembly (LSU):

    -   <https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_009812075.1/>

-   WGS on 6 individuals from Schroeder et al. 2024 (Rolland Lab):

    -   <https://doi.org/10.1002/ece3.10851>

    -   <https://www.ncbi.nlm.nih.gov/bioproject/1040132>

-   Genbank microsatellite sequences:

    -   <https://www.ncbi.nlm.nih.gov/nuccore/?term=sialia+microsatellite>
